DELETE [OldAdapterAppointments]


INSERT INTO [OldAdapterAppointments]
           ([InternalId]
           ,[LastModified]
           ,[Category]
           ,[Location]
           ,[Content]
           ,[Title]
           ,[DateFrom]
           ,[DateTo]
           ,[ReminderMinutesBeforeStart]
           ,[Notification]
           ,[IsPrivate]
           ,[Priority]
           ,[AppointmentId]
           ,[AdapterId]
           ,[Tag]
           ,[Upload])

SELECT 
			[InternalId]
           ,[LastModified]
           ,[Category]
           ,[Location]
           ,[Content]
           ,[Title]
           ,[DateFrom]
           ,[DateTo]
           ,[ReminderMinutesBeforeStart]
           ,[Notification]
           ,[IsPrivate]
           ,[Priority]
           ,[AppointmentId]
           ,[AdapterId]
           ,[Tag]
           ,[Upload]
	FROM [dbo].[AdapterAppointments]

